### ISSUE TITLE
When I click create project nothing happens

### ISSUE THREAD

**Issue by abrambailey** [Prelang/feedback#27]
I have selected a very unique name for the project and have tried with both types of DB

**Comment by abrambailey** [comment]
POST https://prelang.com/projects 500 (Internal Server Error)send @ projects-38fbdb12635248a4fbc2361c9727759b.js:26rt.extend.ajax @ projects-38fbdb12635248a4fbc2361c9727759b.js:26t.ajax @ projects-38fbdb12635248a4fbc2361c9727759b.js:87t.sync @ projects-38fbdb12635248a4fbc2361c9727759b.js:87Backbone.sync @ projects-38fbdb12635248a4fbc2361c9727759b.js:87n.extend.sync @ projects-38fbdb12635248a4fbc2361c9727759b.js:87n.extend.save @ projects-38fbdb12635248a4fbc2361c9727759b.js:87Prelang.Views.Projects.NewView.i.save @ projects-38fbdb12635248a4fbc2361c9727759b.js:102(anonymous function) @ projects-38fbdb12635248a4fbc2361c9727759b.js:102rt.event.dispatch @ projects-38fbdb12635248a4fbc2361c9727759b.js:25m.handle @ projects-38fbdb12635248a4fbc2361c9727759b.js:24

**Comment by eriknomitch** [comment]
Sorry about that @abrambailey.  I'm guessing this is a temporary issue (i.e., it has to do with how Heroku, etc. is behaving right now) I'm going to close the issue but I'm going to email you right now.

**Comment by eriknomitch** [comment]
Okay, this is all fixed.  Thanks for the report @abrambailey.
